# Generated by Django 5.2.1 on 2025-05-12 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cauth.tariff'),
        ),
    ]
