# Generated by Django 5.2.1 on 2025-05-22 04:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0004_user_language'),
        ('main', '0006_remove_question_prompt_questiongroup_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='active_days',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='daily_limit',
        ),
        migrations.AddField(
            model_name='tariff',
            name='description',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='tokens',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='TariffTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cauth.tariff')),
            ],
            options={
                'unique_together': {('tarif', 'language')},
            },
        ),
        migrations.DeleteModel(
            name='UserTariffHistory',
        ),
    ]
