# Generated by Django 5.2.1 on 2025-05-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0005_remove_tariff_active_days_remove_tariff_daily_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='name',
        ),
    ]
