# Generated by Django 5.2.1 on 2025-05-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0006_remove_tariff_description_remove_tariff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tariff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_user',
            field=models.BooleanField(default=False),
        ),
    ]
