# Generated by Django 5.2.1 on 2025-05-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0007_remove_user_tariff_user_is_active_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
