# Generated by Django 5.2.1 on 2025-05-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauth', '0008_user_total_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
