services:

  app:
    image: ${MY_IMAGE}
    # volumes:
    #   - .:/app  
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             uvicorn config.asgi:application --host 0.0.0.0 --port 8000"

  db:
    image: postgres:14.0-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /root/docker_volume:/var/lib/postgresql/data/
    ports:
      - "5438:5432"
