# Generated by Django 4.2.1 on 2025-06-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Narxi')),
                ('payment_type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('stripe', 'Stripe')], default='click', verbose_name='Status')),
                ('status', models.SmallIntegerField(choices=[(1, 'created'), (2, 'on process'), (3, 'verified'), (4, 'delivered'), (0, 'cancelled ')], default=1, verbose_name='Status')),
                ('payment_status', models.SmallIntegerField(choices=[(0, "To'lanmadi"), (1, "To'landi")], default=0, verbose_name="To'lov holati")),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cauth.tariff', verbose_name='Tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma qiluvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
