# Generated by Django 5.2.1 on 2025-05-23 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cauth', '0009_alter_user_total_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Narxi')),
                ('payment_type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('stripe', 'Stripe')], default='click', verbose_name='Status')),
                ('status', models.SmallIntegerField(choices=[(1, 'created'), (2, 'on process'), (3, 'verified'), (4, 'delivered'), (0, 'cancelled ')], default=1, verbose_name='Status')),
                ('payment_status', models.SmallIntegerField(choices=[(0, "To'lanmadi"), (1, "To'landi")], default=0, verbose_name="To'lov holati")),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cauth.tariff', verbose_name='Tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma qiluvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='PaycomTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycom_transaction_id', models.CharField(max_length=255, unique=True)),
                ('paycom_time', models.CharField(max_length=15)),
                ('paycom_time_datetime', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('receivers', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
    ]
