# Generated by Django 5.2.1 on 2025-05-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_category/'),
        ),
    ]
