# Generated by Django 5.2.1 on 2025-05-15 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projectcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='boolean',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='value',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('select', 'Select')], max_length=10),
        ),
        migrations.CreateModel(
            name='QuestionOptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.questionoption')),
            ],
            options={
                'unique_together': {('question_option', 'language')},
            },
        ),
    ]
