# Generated by Django 5.2.1 on 2025-05-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_questionprompttranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='prompt',
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together={('category', 'order')},
        ),
    ]
