# Generated by Django 5.2.1 on 2025-05-26 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_question_prompt_questiongroup_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPromptTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='main.projectcategory')),
            ],
            options={
                'unique_together': {('question', 'language')},
            },
        ),
    ]
