# Generated by Django 5.2.1 on 2025-05-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projectprompttranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectprompttranslation',
            old_name='question',
            new_name='project_category',
        ),
        migrations.AlterUniqueTogether(
            name='projectprompttranslation',
            unique_together={('project_category', 'language')},
        ),
    ]
