# Generated by Django 5.2.1 on 2025-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_question_projectprompttranslation_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('select', 'Select'), ('free_answer', 'free_answer')], max_length=15),
        ),
    ]
