# Generated by Django 4.2.1 on 2025-06-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionoption",
            name="boolean",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
