# Generated by Django 4.2.1 on 2025-06-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0010_questionoption_boolean"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translations", models.JSONField()),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.language"
                    ),
                ),
            ],
        ),
    ]
