# Generated by Django 4.2.1 on 2025-06-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
    ]
