# Generated by Django 5.2.1 on 2025-05-19 03:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('main', '0004_alter_projectcategorytranslation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='project',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='main.projectcategory'),
            preserve_default=False,
        ),
    ]
