# Generated by Django 5.2.1 on 2025-05-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userchat_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
    ]
