# Generated by Django 5.2.1 on 2025-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_useropenaichathistoryquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='useropenaichathistoryquestion',
            name='boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
