# Generated by Django 5.2.1 on 2025-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_useropenaichathistoryquestion_boolean'),
        ('main', '0006_remove_question_prompt_questiongroup_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useropenaichathistoryquestion',
            name='question_option',
        ),
        migrations.AddField(
            model_name='useropenaichathistoryquestion',
            name='question_options',
            field=models.ManyToManyField(to='main.questionoption'),
        ),
    ]
