# Generated by Django 5.2.1 on 2025-05-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_useropenaichathistoryquestion_question_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useropenaichathistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='useropenaichathistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='useropenaichathistoryquestion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='useropenaichathistoryquestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='useropenaichathistoryquestion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='useropenaichathistoryquestion',
            name='updated_by',
        ),
    ]
